name: Deploy to AWS Server

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

    - name: Deploy to AWS
      run: |
        ssh -o StrictHostKeyChecking=no username@your-server-ip << 'EOF'
        cd /path/to/your/project
        git pull origin main
        # Add commands to build/restart the app, e.g.:
        # npm install
        # pm2 restart app
        EOF
